services:
  # Spring Boot Backend Web Service
  - type: web
    name: tradingco-backend
    env: docker
    dockerContext: ./tradingco-backend
    dockerfilePath: ./tradingco-backend/Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false # Paste: jdbc:postgresql://ep-bitter-night-a6qq1frm.us-west-2.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        sync: false # Paste: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false # Paste: npg_8qufKUTMI7lQ
      - key: SPRING_REDIS_HOST
        sync: false # Paste host of tradingco-redis-t9vu
      - key: SPRING_REDIS_PORT
        sync: false # Paste port of tradingco-redis-t9vu
      - key: SPRING_REDIS_PASSWORD
        sync: false # Paste password of tradingco-redis-t9vu
      - key: JWT_SECRET
        generateValue: true


